version: 1.0
provider:
  name: openfaas
functions:
  openfaas-imagecrawlerdemux:
    lang: go
    handler: ./openfaas-imagecrawlerdemux
    image: servernull/openfaas-imagecrawlerdemux:0.1.0
    environment:
      read_timeout: 120
      write_timeout: 120
      exec_timeout: 120
